apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: kube-prometheus
    role: alert-rules
  name: kube-prometheus-node-custom-alarm
spec:
  groups:
  - name: node.rules
    rules:
    - alert: Node-Disk-Space-Low
      expr: predict_linear(node_filesystem_free[6h], 3600 * 24) < 0
      for: 30m
      labels:
        severity: warning
        service: node
        cluster: test1
      annotations:
        description: A node is reporting low disk space. 
        summary: Action is required on a node.
   
    
